### ISSUE TITLE
api next query string is bad

### ISSUE THREAD

**Issue by zhen-kuo** [PandoraPay/go-pandora-pay#16]
https://github.com/PandoraPay/go-pandora-pay/blob/0eb16dcd9c20e71a92ac4132a40dcffbc4c1e167/network/api/api_common/api_method_accounts_txs.go#L43-L60

api next query string is stupid. maybe it should be start !

**Comment by ibudisteanu** [comment]
This API route is used in the web wallet to display last N transactions. I don't see any issue with this route.

**Comment by zhen-kuo** [comment]
use start query string. it is easier for developers to understand how to use it.

**Comment by zhen-kuo** [comment]
better here. look. https://github.com/PandoraPay/go-pandora-pay/pull/17

**Comment by ibudisteanu** [comment]
I checked your pull request. I will not accept it right now as it will broke the web wallet for the testnet.

**Comment by ibudisteanu** [comment]
I decided to fix the web wallet, but I have noticed your pull request has many issues...
