### ISSUE TITLE
bug. web wallet wait 10 seconds

### ISSUE THREAD

**Issue by xiangwei22** [PandoraPay/go-pandora-pay#19]
https://github.com/PandoraPay/go-pandora-pay/blob/224bd852ab2c3426fb4e3882b64fb2d7a6793ede/blockchain/blockchain_extra.go#L146-L148

this makes web wallet wait 10 seconds. it should be removed.

**Comment by xiangwei22** [comment]
xiangwei22:patch-1

**Comment by ibudisteanu** [comment]
I have merged your pull request

**Comment by xiangwei22** [comment]
thank you !!
