### ISSUE TITLE
disable balance decryptor automatic init

### ISSUE THREAD

**Issue by xiangwei22** [PandoraPay/go-pandora-pay#3]
https://github.com/PandoraPay/go-pandora-pay/blob/4da7a826ff544cb25b95e71765173e0aeccece74/start/start.go#L91-L97

disable balance decryptor if not required. for example a full-node might never use the balance decryptor. either it should be initialized when needed or there should be a mechanism to optionally disable it.

**Comment by ibudisteanu** [comment]
see commits 
6dfc1865cf86d14ca3192325821465778fe37f9e
56b1d9733e14d725617ab92e399ef6989242a3fe

**Comment by xiangwei22** [comment]
thanks
