### ISSUE TITLE
update wallet to invalidate cached wasm and other assets ?

### ISSUE THREAD

**Issue by xiangwei22** [PandoraPay/go-pandora-pay#6]
update wallet to invalidate cached wasm and other assets files. like versioning the wasm files.

**Comment by ibudisteanu** [comment]
So, this question is regarding the web wallet? Why did you open a github issue here ?

**Comment by ibudisteanu** [comment]
Does this commit https://github.com/PandoraPay/PandoraPay-wallet/commit/a986261ba7296a94a5053bafa65e86414f0a031a solves your issue ?

**Comment by xiangwei22** [comment]
thank you. issue solved
