### ISSUE TITLE
feature request. argument for table size

### ISSUE THREAD

**Issue by xiangwei22** [PandoraPay/go-pandora-pay#8]
feature request. argument for table size

https://github.com/PandoraPay/go-pandora-pay/blob/2226655c29047ada6704b4b7f9d2719352984f1e/start/start.go#L95

**Comment by ibudisteanu** [comment]
Actually this is a great suggestion. Table size 24 uses about 64-128 MB ram, and it might now work on some machines that have very low specs (vps etc )

**Comment by ibudisteanu** [comment]
Is this commit https://github.com/PandoraPay/go-pandora-pay/commit/96d1199a4098657669cd3b094a47f1608fc01e53 solving your feature request ?

**Comment by xiangwei22** [comment]
yes
