### ISSUE TITLE
bug in start.go 

### ISSUE THREAD

**Issue by xiangwei22** [PandoraPay/go-pandora-pay#9]
https://github.com/PandoraPay/go-pandora-pay/blob/5a77f8e932a48b2c4bcfce7becfd945dee9a19cf/start/start.go#L94-L95

i think here must be --balance-decryptor-table-size

**Comment by ibudisteanu** [comment]
Right.  See commit. https://github.com/PandoraPay/go-pandora-pay/commit/debddf7c3b1c8b282b126976c90d2a2420322c33
